version: '3'

services:
  server:
    build: ../part_5
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    ports:
      - 80:8080
